@startuml
skinparam style strictuml
skinparam PackageBackgroundColor #f9f9f9



class FlaskApp << (C, #FFAAAA) >> {
    + route_login()
    + route_recommend()
    + route_cookbook()
    --
    * Manages Session (24h)
    * Integrates Sentry
}

package "Data Models (ORM Layer)" {
  class User {
    + id: int
    + username: str
    + password_hash: str
    + location: str
    + role: Enum
  }

  class Cookbook {
    + id: int
    + user_id: int
  }

  class Recipe {
    + id: int
    + title: str
    + ingredients: text
    + creator_id: int
    + like_count: int
  }
}

package "Recommendation_data" {
  class Recommendations {
    + calculate_t_distribution(data: list)
    + run_graph_recommendation(user_id)
    --
    * Uses SciPy & NetworkX
  }

}

package "APIs"{
  class ExternalApiService {
    + autocomplete_ingredient(query: str)
    --
    * Uses Spoonacular/AI API
  }
}

' Relationships
User "1" -- "1" Cookbook : owns
Cookbook "1" -- "*" Recipe : contains
Recipe "*" -- "1" User : created_by

FlaskApp ..> Recommendations : requests math logic
FlaskApp ..> ExternalApiService : fetches ingredients
FlaskApp ..> User : queries data

@enduml